services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_AUTH_USER}
      MYSQL_PASSWORD: ${DB_AUTH_USER_PASS}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file: ".env"
